### ISSUE TITLE
Find more sources of text data - which sources?

### ISSUE THREAD

**Issue by ernestguevarra** [como-ph/comotext#7]
[] statements, press release and resolutions from other IATF members

[] Office of the president statements?

**Comment by JohnRobert01** [comment]
Will do search for more releases and resolutions

**Comment by ernestguevarra** [comment]
See my blog post on this. I think for current purpose, let's decide to focus on using IATF resolutions for now and then limit the scope of the questions we want to answer to those that can be answered using the IATF text dataset. I think this will make it more manageable to accomplish for a first output and then we expand the project afterwards as we add more data.
